spring:
  application:
    name: energycoop
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 5
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect

scheduling:
  graig-fatha:
    schedule:
      energy-yield: "15 */15 * * * *"
      performance: "5 0 */6 * * *"

okta:
  oauth2:
    issuer: ${AUTH0_ISSUER}
    audience: ${AUTH0_AUDIENCE}
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_SECRET}
    groupsClaim: permissions

external:
  api:
    graig-fatha:
      url: ${API_GRAIG_FATHA_URL}
      tid: ${API_GRAIG_FATHA_TID}
      key: ${API_GRAIG_FATHA_KEY}

site:
  rates:
    gf: ${SITE_RATES_GF}
  capacity:
    gf: ${SITE_CAPACITY_GF}
  share-price:
    gf: ${SITE_SHARE_PRICE_GF}
  first-year-operation-end:
    gf: ${SITE_FIRST_YEAR_OP_END_GF}

alerts:
  enabled: ${ALERTS_ENABLED}
  discord:
    webhook-url: ${ALERTS_DISCORD_WEBHOOK_URL}
  thresholds:
    availability: ${ALERTS_THRESHOLDS_AVAILABILITY}
    failure-time: ${ALERTS_THRESHOLDS_FAILURE_TIME}

allowedOrigins: http://localhost:4200,https://user-dashboard-staging.windcoop.co.uk
