[versions]
# Library versions
springDocVersion = "2.8.13"

mockitoVersion = "5.20.0"

auth0Version = "3.0.8"

apacheCommonsVersion = "3.20.0"

postgresqlVersion = "42.7.8"

# Plugin versions
springBootVersion = "4.0.0"

springDependencyManagementVersion = "1.1.7"

asciiDoctorVersion = "4.0.5"

pdfBoxVersion = "3.0.6"

[libraries]
springDoc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springDocVersion" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockitoVersion" }
auth0 = { group = "com.okta.spring", name = "okta-spring-boot-starter", version.ref = "auth0Version" }
apache-commons-lang = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommonsVersion" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresqlVersion" }
pdfbox = { group = "org.apache.pdfbox", name = "pdfbox", version.ref = "pdfBoxVersion" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBootVersion" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }
asciiDoctor = { id = "org.asciidoctor.jvm.convert", version.ref = "asciiDoctorVersion" }
